processed 5 tasks
task 0 lines 3-11:  publish [// Bytecode version v8]
task 1 lines 15-130:  publish [// Bytecode version v8]
task 2 lines 134-134:  run 0x42::caller::init --signers 0x42
task 3 lines 136-136:  run 0x42::caller::callback_ok
return values: true
task 4 lines 138-138:  run 0x42::caller::callback_fails --verbose
Error: Function execution failed with VMError: {
    message: Resource `0x42::caller::R` cannot be accessed because of active reentrancy of defining module.,
    major_status: RUNTIME_DISPATCH_ERROR,
    sub_status: None,
    location: 0x42::caller,
    indices: [],
    offsets: [(FunctionDefinitionIndex(4), 3)],
    exec_state: Some(ExecutionState { stack_trace: [(Some(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000042, name: Identifier("callee") }), FunctionDefinitionIndex(0), 2), (Some(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000042, name: Identifier("caller") }), FunctionDefinitionIndex(1), 5)] }),
}
